avocado/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

# from avocado import settings
# from django.templatetags.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
import core.views as views

urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name='index'),
    path('contact/', views.contact, name='contact')
]

clients/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class Client(models.Model):
    image = models.ImageField(_("Imagen CLiente"), upload_to='client/', height_field=None, width_field=None, max_length=None)
    name = models.CharField(_("Nombre Empresa"), max_length=50)
    description = models.CharField(_("Descripcion"), max_length=100)
    created = models.DateTimeField( auto_now=False, auto_now_add=True)
    modified = models.DateTimeField( auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.name
    

contact/models.py
from django.db import models
from django.utils.translation import gettext as _


# Create your models here.

class Contact(models.Model):
    name = models.CharField(_("Nombre:"), max_length=30)
    email = models.EmailField(_("Correo"), max_length=100)
    phone = models.CharField(_("Numero telefonico"), max_length=12)
    message = models.TextField(_("Mensaje"))
    created = models.DateTimeField( auto_now=False, auto_now_add=True)
  

    def __str__(self):
        return self.name
    

core/models.py
from django.db import models

# Create your models here.

services/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.

class Service(models.Model):
    image = models.ImageField(_("Imagen servicio"), upload_to='service/', height_field=None, width_field=None, max_length=None)
    title = models.CharField(_("Titulo"), max_length=50)
    body = models.TextField(_("Detalles"))
    created = models.DateTimeField( auto_now=False, auto_now_add=True)
    modified = models.DateTimeField( auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title
    

social/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.

class Social(models.Model):
    photo = models.ImageField(_("Fotos"), upload_to='social/', height_field=None, width_field=None, max_length=None)
    title = models.CharField(_("Nombre de la red"), max_length=50)
    url = models.URLField(_("Direccion de la red"), max_length=200)

    def __str__(self):
        return self.title
    

contact/forms.py

from django.forms import ModelForm
from .models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone', 'message'] 

clients/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import redirect, render
from django.views.generic.base import TemplateView
from services.models import Service
from clients.models import Client
from contact.forms import ContactForm
from social.models import Social
from django.urls import reverse

# Create your views here.


class IndexTemplateView(TemplateView):
    template_name = "core/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["services_list"] = Service.objects.all()
        context["clients_list"] = Client.objects.all()
        context["social_list"] = Social.objects.all()
        # context["form"] = form;
        return context


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST);
        if form.is_valid():
            form.save()
            return redirect(reverse('core:index')+'?ok')
            # var = form['name']
            # import pdb
            # pdb.set_trace()
            

        else:
            # import pdb
            # pdb.set_trace()
            return redirect(reverse('core:index')+'?notok')
            # return render(request, 'core/index.html', {'form':form})
            


    return redirect('/')
        
        


        # form.name = 
   
   
    
    

services/views.py
from django.shortcuts import render
from services.models import Service

# Create your views here.


# class ServiceListView(ListView):
#     model = Service
#     template_name = "services/service_list.html"
#     ordering  =('-created')
#     context_object_name = 'object_list'

social/views.py
from django.shortcuts import render

# Create your views here.

contact/templates/contact/contact.html
{% extends 'index.html' %}

{% block contact %}
{{form}}
{% endblock contact %}

core/templates/core/about.html
<!-- About-->
{% load static %}
<section class="page-section" id="about">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">QUIENES SOMOS</h2>
            <h3 class="section-subheading text-muted">Pasion por las paltas</h3>
        </div>
        <ul class="timeline">
            <li>
                <div class="timeline-image"><img class="rounded-circle img-fluid" src="{% static 'assets/img/about/1.jpg' %}" alt="" />
                </div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4>2020</h4>
                        <h4 class="subheading">Inicio</h4>
                    </div>
                    <div class="timeline-body">
                        <p class="text-muted">El Comité de Paltas de Chile es una asociación independiente, que
                            representa a agricultores, productores, comercializadores y distribuidores chilenos, cuyo
                            propósito es fomentar el desarrollo sustentable de la industria y difundir sus buenas
                            prácticas.
                            Nuestra misión es promover el consumo de palta chilena en Chile y el mundo, además de
                            supervisar la calidad de la fruta que se exporta velando porque esta sea la mejor y cumpla
                            con los estándares ambientales correspondientes.</p>
                    </div>
                </div>
            </li>

        </ul>
    </div>
</section>

core/templates/core/masthead.html
<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <div class="masthead-subheading">Que alegria verte aqui</div>
        <div class="masthead-heading text-uppercase">Bienvenido a Avocado SPA</div>
        <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" style="background-color: #0b2e13;
  border-color: #0b2e13;" href="#services">Comenzemos</a>
    </div>
</header>

templates/core/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Agency - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %} " />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet"
        type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %} " rel="stylesheet" />
</head>

<body id="page-top">

    

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="{% static 'assets/img/navbar-logo.svg' %}"
                    alt="" /></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ml-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ml-auto">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">Historia</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">Servicios</a></li>
                    <!-- <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a></li> -->
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#clients">Clientes</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contacto</a></li>
                </ul>
            </div>
        </div>
    </nav>




    <!-- Masthead -->
    {% include 'core/masthead.html' %}
    <!-- About -->
    {% include 'core/about.html' %}
    <!-- Services -->
    <section class="page-section" id="services">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Nuestros Servicios</h2>
                <h3 class="section-subheading text-muted">Te va a encantar nuestra propuesta</h3>
            </div>
            <div class="row text-center">
                {% for service in services_list %}
                <div class="col-md-4">
                    <img src="{{service.image.url}}" alt="" srcset="" class="img-thumbnail"
                        style="height: 200px; width: 200px;">
                    <h4 class="my-3">{{service.title}}</h4>
                    <p class="text-muted">{{service.body}}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Clients -->
    <section class="page-section bg-light" id="clients">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Nuestros Clientes</h2>
                <h3 class="section-subheading text-muted">Ellos confian en nosotros</h3>
            </div>
            <div class="row">
                {% for client in clients_list %}
                <div class="col-lg-4">
                    <div class="team-member">
                        <img class="mx-auto rounded-circle" src="{{client.image.url}}" alt="" />
                        <h4>{{client.name}}</h4>
                        <p class="text-muted">{{client.description}}</p>
                        {% comment %} <a class="btn btn-dark btn-social mx-2" href="#!"><i
                                class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                        {% endcomment %}
                    </div>
                </div>

                {% endfor %}
            </div>
            <div class="row">
                <div class="col-lg-8 mx-auto text-center">
                    <p class="large text-muted">
                    Unete como se unieron ellos, te esperamos</p>
                </div>
            </div>
        </div>
    </section>

    
   
    <!-- Contact-->
    <section class="page-section" id="contact">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Contactanos</h2>
                <h3 class="section-subheading text-muted">Estamos aqui para tus dudas</h3>
            </div>
            <!-- novalidate="novalidate" -->
            <form id="contactForm" name="sentMessage" method="post" 
                action="{% url 'core:contact' %}">
                {% csrf_token %}
                {% comment %} {{form}} {% endcomment %}
                <div class="row align-items-stretch mb-5">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input class="form-control" name="name" id="name" type="text" placeholder="Tu Nombre *"
                                required="required" data-validation-required-message="Porfavor" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group">
                            <input class="form-control" name="email" id="email" type="email" placeholder="Tu Email *"
                                required="required"
                                data-validation-required-message="Please enter your email address." />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group mb-md-0">
                            <input class="form-control" name="phone" id="phone" type="tel" placeholder="Tu Telefono *"
                                required="required"
                                data-validation-required-message="Please enter your phone number." />
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-group-textarea mb-md-0">
                            <textarea class="form-control" name="message" id="message" placeholder="Tu Mensaje *"
                                required="required"
                                data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                </div>
                <div class="text-center">
                    <div id="success"></div>
                    <input class="btn btn-primary btn-xl text-uppercase" id="sendMessageButton" type="submit"
                        value="Send">
                    <!-- <button class="btn btn-primary btn-xl text-uppercase" id="sendMessageButton" type="submit">Send -->
                    <!-- Message</button> -->
                </div>
            </form>
        </div>
    </section>
    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-left">Copyright © Your Website 2020</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    {% for social in social_list %}
                    <a class="btn btn-dark btn-social mx-2" href="{{social.url}}"> <img src="{{social.photo.url}}" alt="" srcset="" height="50px" width="50px"> </a>
                    {% endfor %}
                </div>
                <div class="col-lg-4 text-lg-right">
                    <a class="mr-3" href="#!">Privacy Policy</a>
                    <a href="#!">Terms of Use</a>
                </div>
            </div>
        </div>
    </footer> 
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Contact form JS-->
    {% comment %}
    <script src="{% static 'assets/mail/jqBootstrapValidation.js' %}"></script> {% endcomment %}
    <script src="{% static 'assets/mail/contact_me.js' %}"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %} "></script>
    <script src="{% static 'js/bootstrap.js' %} "></script>
    {% if 'notok' in request.GET %}
    <script defer>alert('No se pudo procesar tu solicitud')</script>
    {% elif 'ok' in request.GET %}
    <script defer>alert('Su consulta se envio exitosamente, pronto nos pondremos en contacto')</script>
    
    {% endif %}



</body>

</html>